name: Create Issue
description: Create a github issue on workflow failure or close an issue on success

runs:
  using: "composite"
  steps:
    - name: Create or close issue
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          console.log("WIP")
          console.log(context)
