name: Create Issue
description: Create a github issue on workflow failure or close an issue on success

inputs:
  success:
    description: "Is the workflow succeeding"
    required: true
    type: bool
runs:
  using: "composite"
  steps:
    - name: Create or close issue
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          console.log("WIP")
          console.log(context)
          console.log(context.runId)
          run = await github.rest.actions.getWorkflowRun( {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId,
          })
          console.log(run)


          if (${{ inputs.success }}) { 
            console.log("succeeding. TODO")
          } else {
            console.log("failing. TODO: file issue")
            # find existing issue
            reponame = context.repo.owner + "/" + context.repo.repo
            title = "[bug]: " + context.workflow
            const issues = await github.rest.search.issuesAndPullRequests({
              q:  title + "+label:bug+state:open+type:issue+repo:" + reponame,
            })
            console.log(issues)
            if (issues.data.total_count == 0) {
              # File issue
            } else {
              console.log("issue exists already, not filing a new one")
            }
          }
